### ISSUE TITLE
Two containers can transfer files between each other

### ISSUE THREAD

**Issue by lambdakilo** [dssystems22/tunein2p2p#10]

**Comment by liyang19960201** [comment]
https://docs.docker.com/engine/reference/commandline/cp/  //docker copy data 
https://docs.docker.com/storage/volumes/
https://phoenixnap.com/kb/how-to-share-data-between-docker-containers //docker share data via volume
https://codeonby.com/2022/03/28/file-transfer-in-python-3/ file transfer between client and server by python



http://pymotw.com/2/socket/tcp.html ==>tcp for a sever and client tutorial 

https://github.com/nikhilroxtomar/File-Transfer-using-TCP-Socket-in-Python3/commit/720d1d767126b5b69962f3c34a76bee42b39b08b
==>using a tcp connection to transfer file


https://benediktkr.github.io/dev/2016/02/04/p2p-with-twisted.html==>messing with Json

**Comment by lambdakilo** [comment]
Not going to be implemented using containers.
